import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ItemsPlaylistService {

  constructor() { }

  private teamixVol1 =
    "Beach Boii - Rude (DJ RooBen Edit)\n"
    + "Bruno Mars X Cardi B X Bee Gees - Finesse Vs. Staying Alive (Serafin Finesse Edit - DJ RooBen Fix)\n"
    + "Cardi B & 21 Savage - Bartier Cardi (Roe Hyams Extended mix)\n"
    + "Cardi B Feat 21 Savage - Bartier Cardi (DJ RooBen Redrum)\n"
    + "Cardi B Feat 21 Savage - Bartier Cardi (DJ RooBen Redrum)[Extended]\n"
    + "Charlie Puth - How Long (TeaMix 1 Dudu A'S)\n"
    + "Clean Bandit Ft. Julia Michaels - I Miss You (DJ RooBen Club Edit)\n"
    + "Clean Bandit Ft. Julia Michaels - I Miss You (DJ RooBen Extended Club Edit)\n"
    + "Dj Rapture Ft. Dozay - Jiggle (DJ RooBen Extended)\n"
    + "DJ Snake & Lauv - A Different Way (DJ RooBen Redrum)\n"
    + "Enrique Iglesias Ft. Bad Bunny - El Bano (DJ RooBen Edit)\n"
    + "Enrique Iglesias Ft. Rotem Cohen & Descemer Bueno - Subeme La Radio (DJ RooBen Edit)\n"
    + "Flo Rida, Maluma - Hola (Roe Hyams Redrum)\n"
    + "Gucci Mane - Mall (DJ RooBen Redrum)\n"
    + "Jason Derulo Ft. French Montana - Tip Toe ( Dj Sagiv Alfasi Edit )\n"
    + "Jason Derulo Ft. French Montana - Tip Toe (DJ RooBen Redrum)\n"
    + "Migos - Superstars (DJ RooBen Extended)\n"
    + "סטטיק ובן אל תבורי - נמסטה(Dj Sagiv Extended)\n"
    + "עידו ונה - היי בייב (TeaMix 1 Dudu A'S)\n"
    + "שרית חדד - אמן (TeaMix 1 Dudu A'S)\n";

  private teamixVol2 =
    "BlocBoy JB feat. Drake - Look Alive (TeaMix 2 - Sagiv Alfasi Transitions 100-70)\n"
    + "Clean Bandit - I Miss You (TeaMix 2 - Dudu A'S Redrum)\n"
    + "Daniel Yafe - If It's Love (TeaMix 2 - Daniel Zadka Remix - RooBen Edit)\n"
    + "Drake - God's Plan (TeaMix 2 - Roe Hyams Short Edit)\n"
    + "Eliad - Weekend (TeaMix 2 - Dudu A'S Redrum)\n"
    + "Farruko El Micha - Fuego (TeaMix 2 - Roe Hyams Extended Mix)\n"
    + "Gucci Mane - Smiling in the Drought (TeaMix 2 - RooBen Redrum)\n"
    + "Honorebel ft Charly Black, Pitbull & Julie Elody - Your Love (TeaMix 2 - RooBen Extended)\n"
    + "Huncho Jack, Travis Scott & Quavo Feat Takeoff - Eye 2 Eye (TeaMix 2 - RooBen Redrum)\n"
    + "Inna - Me Gusta (TeaMix 2 - Sagiv Alfasi Edit)\n"
    + "Ivri Lider X Stephane- Moogzam (TeaMix 2 - RooBen Extended)\n"
    + "J Balvin & Pitbull Feat. Camila Cabello - Hey Ma (TeaMix 2 - More D' More Edit)\n"
    + "J. Balvin, Jeon, Anitta - Machika (TeaMix 2 - RooBen Edit)\n"
    + "Jay Rock, Kendrick Lamar, Future, James Blake - King's Dead (TeaMix 2 - Sagiv Alfasi Extended)\n"
    + "Lior Narkis Feat. Vivo - Full Moon (TeaMix 2 - RooBen Fix)\n"
    + "Luis Fonsi & Demi Lovato - Echame La Culpa (TeaMix 2 - Nejtrino & Baur Dudu A'S Edit)\n"
    + "Migos - Superstars (TeaMix 2 - Roe Hyams Redrum)\n"
    + "Nasrin Kadri - Tomru Lo (TeaMix 2 - RooBen Extended)\n"
    + "Reik Ft. Wisin & Ozuna - Me Niego (TeaMix 2 - RooBen Edit)\n"
    + "Romeo Santos Feat. Ozuna - Sobredosis (TeaMix 2 - RooBen Club Mix)\n"
    + "Romeo Santos Feat. Ozuna - Sobredosis (TeaMix 2 - RooBen Extended Club Mix)\n"
    + "Sean Paul & David Guetta feat. Becky G- Mad Love (TeaMix 2 - Sagiv Alfasi Edit)\n"
    + "Sofia Reyes, De La Ghetto, Jason Derulo - 1, 2, 3 (TeaMix 2 - RooBen Edit)\n"
    + "Zafrir Ifrach - Sweet Dream (TeaMix 2 - Dudu A'S Edit)\n";

  private teamixVol3 =
    "BlocBoy JB Ft. Drake - Look Alive (TeaMix 3 - Roe Hyams Extended)\n"
    + "Buddy , A$AP Ferg - Black (TeaMix 3 - Sagiv Alfasi Edit)\n"
    + "Dudu Aharon - Baby (TeaMix 3 - Dudu A'S Redrum)\n"
    + "Enrique Iglesias Ft. Bad Bunny & Natti Natasha - El Bano (Remix) (TeaMix 3 - RooBen Edit)\n"
    + "Hoodcelebrityy - Walking Trophy (TeaMix 3 - RooBen Redrum) \n"
    + "Iggy Azalea - Mo Bounce (TeaMix 3 - More D'More Edit)\n"
    + "Katriks & Doron Biton - Gucci And Prada (TeaMix 3 - Dudu A'S Redrum)\n"
    + "Lil Dicky Ft. Chris Brown - Freaky Friday (TeaMix 3 - Sagiv Alfasi Acapella In Edit)\n"
    + "Lil Dicky Ft. Chris Brown - Freaky Friday (TeaMix 3 - Sagiv Alfasi Extended) Hook 1st\n"
    + "Luis Fonsi & Demi Lovato - Echame La Culpa (Not On You Remix) (TeaMix 3 - RooBen Edit)\n"
    + "Migos - Narcos (TeaMix 3 - Roe Hyams Extended)\n"
    + "Moshe Peretz & Nasrin Kadri - Haino Shnaim (TeaMix 3 - Dudu A'S Redrum)\n"
    + "Natti Natasha Ft. RKM & Ken-Y - Tonta (TeaMix 3 - RooBen Edit)\n"
    + "Nicky Jam x J. Balvin - X (Equis) (TeaMix 3 - Dudu A'S Edit)\n"
    + "Peled - Ahavtit (TeaMix 3 - RooBen Redrum)\n"
    + "Ramz - Barking (TeaMix 3 - Sagiv Alfasi Edit)\n"
    + "Rich The Kid - Plug Walk (TeaMix 3 - Roe Hyams Extended)\n"
    + "Rich The Kid Ft. Kendrick Lamar - New Freezer (TeaMix 3 - Roe Hyams Extended)\n"
    + "Rotem Cohen ft. Descemer Bueno - Como El Agua (TeaMix 3 - RooBen Club Mix)\n"
    + "Stephane Legar & Itay Levi - Maman (TeaMix 3 - RooBen Extended) - Fix\n"
    + "Vini Vici & Timmy Trumpet Ft. Symphonic - 100 (TeaMix 3 - Sagiv Alfasi Short Edit)\n"
    + "Lior Narkis feat. Vivo - Full Moon (TeaMix 3 - Aviel Mymon Edit)\n"
    + "Yakir Ganon & Mor Ben Yair - Ya' Mama (TeaMix 3 - Aviel Mymon Edit)\n"
    + "Zafrir Ifrach - Sultan (TeaMix 3 - Aviel Mymon Edit)\n";

  private teamixVol4 =
    "21 Savage ft. Metro Boomin - X Bitch (TeaMix 4 - RooBen Redrum) Acapella In\n"
    + "21 Savage ft. Metro Boomin - X Bitch (TeaMix 4 - RooBen Redrum)\n"
    + "Beyonce - Single Ladies 17 (TeaMix 4 - Dudu A'S Edit)\n"
    + "Cardi B ft Bad Bunny & J Balvin - I Like It (TeaMix 4 - RooBen Extended)\n"
    + "Cardi B ft. Migos - Drip (TeaMix 4 - RooBen Extended)\n"
    + "Carnage Ft Lil Yachty - Mase in '97 (TeaMix 4 - Roe Hyams Extended)\n"
    + "Descemer Bueno & Enrique Iglesias Ft. El Micha - Nos Fuimos Lejos (TeaMix 4 - RooBen Edit)\n"
    + "DJ Khaled Ft. Rihanna - Wild Thoughts (TeaMix 4 - Dudu A'S Edit)\n"
    + "Empire Cast Feat. Yazz & Timbaland - Dynasty (TeaMix 4 - More D'More Edit)\n"
    + "Fais - Know You Better (TeaMix 4 - Dudu A'S Redrum)\n"
    + "Famous Dex Ft A$ap Rocky - Pick it Up (TeaMix 4 - Roe Hyams Extended)\n"
    + "Iamsu - On My Own (TeaMix 4 - RooBen Extended)\n"
    + "Logic & Marshmello - Everyday (TeaMix 4 - Sagiv Alfasi Edit)\n"
    + "Maddix, KEVU Vs. Netta - Bang Toy (TeaMix 4 - Sagiv Alfasi Mushup)\n"
    + "Migos Feat. Drake - Walk It Talk It (TeaMix 4 - RooBen Redrum)\n"
    + "Netta - Toy (TeaMix 4 - Ran Ziv & Tal Mor - Dudu A'S Edit)\n"
    + "Nicki Minaj - Chun-Li (TeaMix 4 - Sagiv Alfasi Edit)\n"
    + "Prince Royce - El Clavo (TeaMix 4 - Sagiv Alfasi Edit )\n"
    + "Sean Paul & Major Lazer - Tip Pon It (TeaMix 4 - Roe Hyams Extended)\n"
    + "Sean Paul feat Major Lazer - Tip Pon It (TeaMix 4 - Sagiv Alfasi Edit)\n"
    + "Sofia Reyes Feat. Jason Derulo & De La Ghetto - 1, 2, 3 (TeaMix 4 - More D'More Edit)\n"
    + "Stephane Legar & Itay Levi - MAMAN (TeaMix 4 - Dudu A'S Redrum)\n"
    + "The Kemist & DJ BrainDeaD - Mayhem (TeaMix 4 - RooBen Edit)\n"
    + "Tinashe Ft. Ty Dolla Sign & French Montana - Me So Bad (TeaMix 4 - RooBen Redrum)\n";

  private teamixVol5 =
    "Avior Malasa - Diamond (TeaMix 5 - Dudu A'S Redrum)\n"
    + "Diplo, French Montana & Lil Pump ft Zhavia Ward - Welcome To The Party (TeaMix 5 - RooBen Extended)\n"
    + "DJ Snake X Siks John Walt X Julian Jordan - The Magenta Riddim Sky (TeaMix 5 - Sagiv Alfasi Transition) 100-128\n"
    + "Eliad - Heavens (TeaMix 5 - Sagiv Alfasi Redrum)\n"
    + "Enrique Iglesias feat. Bad Bunny - El Bano (TeaMix 5 - Dudu A'S Redrum)\n"
    + "Future Ft. Nicki Minaj - You Da Baddest (TeaMix 5 - RooBen Redrum) (Extended)\n"
    + "Future Ft. Nicki Minaj - You Da Baddest (TeaMix 5 - RooBen Redrum) Hook 1st\n"
    + "Future Ft. Nicki Minaj - You Da Baddest (TeaMix 5 - RooBen Redrum)\n"
    + "Ivri Lider - My Queen (TeaMix 5 - Dudu A'S Redrum)\n"
    + "Kid Ink - One Time (TeaMix 5 - RooBen Extended)\n"
    + "Major Lazer & Moti - Boom (Fizo Remix - TeaMix 5 - Dudu A'S Edit)\n"
    + "Maor Edri - Allah Ma'ak (TeaMix 5 - RooBen Short Edit)\n"
    + "Metallica - Enter Sandman (TeaMix 5 - Joel Fletcher & Reece Low - RooBen Short Edit)\n"
    + "Michael Swissa & Young Heffner - Pashtida (TeaMix 5 - Roe Hyams Extended)\n"
    + "MR.BLACK x Diego Miranda X Tiesto XDzeko Ft. Preme & Post Malone & The Kemist - Boomshakalak Jackie Chan (TeaMix 5 - Sagiv Alfasi MashUp)\n"
    + "Post Malone & 21 Savage - Rockstar (Nejtrino & Baur Remix - TeaMix 5 - Dudu A'S Edit)\n"
    + "The Weeknd feat. Kendric Lamar - Pray For Me (TeaMix 5 - Roe Hyams Edit) (Kendric First)\n"
    + "The Weeknd feat. Kendric Lamar - Pray For Me (TeaMix 5 - Roe Hyams Edit)\n"
    + "Tiesto & Dzeko ft Premo & Post Malone - Jackie Chan (TeaMix 5 - Roe Hyams Edit)\n"
    + "Tiesto, KSHMR, Jewelz & Sparks - Secret VS. I Can Fly (TeaMix 5 - RooBen Mashup)\n"
    + "Tyga Ft. Offset - Taste (TeaMix 5 - RooBen Extended)\n"
    + "YBN Nahmir - Bounce Out With That (TeaMix 5 - Roe Hyams Edit)\n";

  private teamixVol6 =
    "6IX9INE - Tati (TeaMix 6 - Roe Hyams Intro)\n"
    + "Borgeous X Wiz Khalifa - All That Dem Boyz (TeaMix 6 - Sagiv Alfasi Mash-Up) (140 - 155 Transition)\n"
    + "BURNS x Maluma x Rae Sremmurd - Hands On Me (TeaMix 6 - Doron Shitrit Edit)\n"
    + "David Guetta & Showtek - Your Love (TeaMix 6 - RooBen Edit)\n"
    + "Drake - I'm Upset (TeaMix 6 - Roe Hyams Intro)\n"
    + "French Montana & Remy Ma - New Thang (TeaMix 6 - Sagiv Alfasi Edit)\n"
    + "Gente de Zona - Te Duele (TeaMix 6 - RooBen Edit)\n"
    + "Gil Vain - Colors (TeaMix 6 - Dudu A'S Redrum)\n"
    + "Lil Skies - Welcome To The Rodeo (TeaMix 6 - Roe Hyams Extended)\n"
    + "Luis Fonsi, Stefflon Don - Calypso (TeaMix 6 - Dudu A'S Edit) V2\n"
    + "Luis Fonsi, Stefflon Don - Calypso (TeaMix 6 - Dudu A'S Edit)\n"
    + "LunchMoney Lewis - Who's Up (TeaMix 6 - Doron Shitrit Extended)\n"
    + "Marshmello & Anne-Marie - Friends (Deejay Killer Remix- TeaMix 6 - Dudu A'S Edit)\n"
    + "Nicki Minaj feat Lil Wayne - Rich Sex (TeaMix 6 - Sagiv Alfasi Edit)\n"
    + "Nicki Minaj ft Ariana Grande - Bed (TeaMix 6 - RooBen Redrum)\n"
    + "Nicky Jam & J Balvin - X (TeaMix 6 - RooBen Mashup)\n"
    + "Ramz - Barking (TeaMix 6 - Doron Shitrit Edit)\n"
    + "Shakira Ft. Maluma - Clandestino (TeaMix 6 - Doron Shitrit Power Edit)\n"
    + "Spankox - To The Club (Hoox Remix - TeaMix 6 - Dudu A'S Edit)\n"
    + "Tee Grizzley ft Chris Brown - Fuck It Off (TeaMix 6 - RooBen Extended)\n"
    + "Tory Lanez ft Ozuna - Pa Mi (TeaMix 6 - RooBen Redrum)\n"
    + "YALO - Waiting For You (TeaMix 6 - RooBen Redrum)\n"
    + "Yellow Claw, MC Kekel, Lil Debbie, Bok Nero, MC Gustta - To the Max (TeaMix 6 - Sagiv Alfasi Edit)\n";

  private teamixVol7 =
    "50 Cent - P.I.M.P. (Hedegaard Remix TeaMix 7 - IdoM Edit)\n"
    + "Arcangel Ft. Bad Bunny - Original (TeaMix 7 - RooBen Intro)\n"
    + "Avicii & Merk & Kremont - Without You (TeaMix 7 - Roe Hyams Short Edit)\n"
    + "Bebe Rexha - Self Control (TeaMix 7 - Dudu A'S Redrum)\n"
    + "Cardi B & Bad Bunny & J Balvin - I Like It (Dillon Francis Remix- TeaMix 7 - Sagiv Alfasi Edit)\n"
    + "Charly Black - More Gal (TeaMix 7 - RooBen Intro)\n"
    + "DJ Snake X Lil Jon - Turn Down For Axum Style (TeaMix 7 - Doron Shitrit Mash-Up)\n"
    + "Drake - Gods Plan (TeaMix 7 - IdoM Edit) 128-77\n"
    + "Drake - In My Feelings (TeaMix 7 - Doron Shitrit Intro)\n"
    + "Iggy Azalea ft Tyga - Kream (TeaMix 7 - Sagiv Alfasi Intro)\n"
    + "Iggy Azalea ft Tyga X Far East Movement- Kream Like a G6 (TeaMix 7 - Sagiv Alfasi Mash-Up)\n"
    + "J balvin - Bonita (TeaMix 7 - Roe Hyams Intro)\n"
    + "J Balvin, Jowell & Randy feat. Nicky Jam, Wisin, Yandel, Ozuna - Bonita (TeaMix 7 - Doron Shitrit Redrum)\n"
    + "Kritical Ft. Eric Tucker & Nick Nack - Cabana (TeaMix 7 - RooBen Intro)\n"
    + "Lil Pump - Drug Addicts (TeaMix 7 - Sagiv Alfasi Redrum)\n"
    + "Robin Schulz - Oh Child (TeaMix 7 - Sagiv Alfasi Redrum)\n"
    + "Stephane Legar - Comme Ci Comme ?a (TeaMix 7 - Roe Hyams Intro)\n"
    + "Ty Dolla $ign, 6LACK, Khalid - OTW (TeaMix 7 - Doron Shitrit Intro)\n"
    + "Tyga Feat. Offset - Taste (TeaMix 7 - IdoM Intro)\n"
    + "אייל גולן - אסתדר לבד (TeaMix 7 - Dudu A'S Redrum)\n"
    + "ליאור נרקיס - איתי לוי & VIVO - מסיבת רווקים (TeaMix 7 - Dudu A'S Darbuka Redrum)\n"
    + "ליאור נרקיס & איתי לוי & VIVO - מסיבת רווקים (Dj Niso Slob Remix - TeaMix 7 - Doron Shitrit Darbuka Edit)\n"
    + "צביקה ברנד & 242 מארחים את אקסום - מסיבת רחוב (TeaMix 7 - RooBen Edit)\n";

  private teamixVol8 =
    "6ix9ine ft Nicki Minaj - FEFE (TeaMix 8 - Sagiv Alfasi Redrum)\n"
    + "Alvaro Soler - La Cintura (TeaMix 8 - Sagiv Alfasi Redrum)\n"
    + "Aya Nakamura - Djadja (TeaMix 8 - Dudu A'S Redrum)\n"
    + "Descemer Bueno & Enrique Iglesias - Nos Fuimos Lejos (TeaMix 8 - Dudu A'S Redrum)\n"
    + "DJ Khaled feat. Justin Bieber - No Brainer (TeaMix 8 - IdoM Redrum)\n"
    + "Drake - In My Feelings (TeaMix 8 - RooBen Redrum) (Extended)\n"
    + "Drake - In My Feelings (TeaMix 8 - RooBen Redrum)\n"
    + "El Chombo - Dame Tu Papi Chulo (TeaMix 8 - IdoM Edit)\n"
    + "Jerry Rivera Ft. Yandel - Mira (TeaMix 8 - RooBen & Simon Extended)\n"
    + "Maître Gims Ft. Lil Wayne - Corazón (TeaMix 8 - Sagiv Alfasi Redrum)\n"
    + "Maluma - Mala M?a (TeaMix 8 - Doron Shitrit Remix)\n"
    + "Omar Rudberg feat. Elias Hurtig - La Mesa (TeaMix 8 - Sagiv Alfasi Redrum)\n"
    + "Wolfine & Maluma - Bella (TeaMix 8 - Dudu A'S Edit)\n"
    + "אביאור מלסה - כמה כמה (TeaMix 8 - RooBen Edit)\n"
    + "סאבלימינל מארח את עמית שגיא - חופשי (TeaMix 8 - Dudu A'S Redrum)\n"
    + "עדן חסון - שיכורים (TeaMix 8 - RooBen Edit) (Extended)\n"
    + "עדן חסון - שיכורים (TeaMix 8 - RooBen Edit) (Hook 1st)\n"
    + "עדן חסון - שיכורים (TeaMix 8 - RooBen Edit)\n"
    + "קטריקס ודורון ביטון - בחופים של תאילנד (TeaMix 8 - Dudu A'S Edit)\n"
    + "קריזמו - מאמין (TeaMix 8 - RooBen Edit)\n";

  private teamixVol9 =
    "Alex Sensation Ft. Nicky Jam - La Diabla (TeaMix 9 - Dudu A'S Redrum)\n"
    + "Barachi Ft. Tory Lanez - Wifey (TeaMix 9 - RooBen Aca In)\n"
    + "Dan Balan feat. Marley Waters - Numa Numa 2 (TeaMix 9 - RooBen Intro)\n"
    + "David Guetta & Steve Aoki ft. Lil Uzi Vert, G-Easy & Molly Mall - Motto (TeaMix 9 - DJ Kuper Transition 100-85)\n"
    + "David Guetta, Bebe Rexha, J Balvin - Say My Name (TeaMix 9 - DJ Kuper 'Only J Balvin' Edit)\n"
    + "DJ Khaled ft. Drake - For Free (TeaMix 9 - DJ Kuper 'On n On' Edit)\n"
    + "DJ Polique ft The Chaze - Dancer (TeaMix 9 - RooBen Intro) (Hook 1st)\n"
    + "DJ Polique ft The Chaze - Dancer (TeaMix 9 - RooBen Intro)\n"
    + "DJ Snake feat Selena Gomez, Cardi B & Ozuna - Taki Taki (TeaMix 9 - IdoM Edit)\n"
    + "Dj Snake ft. Selena Gomez ,Cardi B & Ozuna - Taki Taki (TeaMix 9 - Sagiv Alfasi Redrum)\n"
    + "Jonn Hart feat Too Short - Whistle (TeaMix 9 - RooBen Intro)\n"
    + "Kanye West & Lil Pump X Banza & Kjuus- I Love It (TeaMix 9 - RooBen Transition 104-124)\n"
    + "Kanye West feat Lil Pump & Adele Givens - I Love It (TeaMix 9 - IdoM Intro)\n"
    + "Lil Pump ft. Kanye West - I Love It (TeaMix 9 - DJ Kuper Transition 90-104)\n"
    + "Nio Garcia & Casper Magico - Quien Diria (TeaMix 9 - Sagiv Alfasi Redrum)\n"
    + "Ozuna - Devuelveme (TeaMix 9 - RooBen Intro)\n"
    + "Pitbull, El Chombo Y Karol G ft Cutty Ranks - Dame Tu Cosita (TeaMix 9 - RooBen Intro)\n"
    + "Rak Su Banx Ranx - Pyro Ting (TeaMix 9 - Sagiv Alfasi Redrum)\n"
    + "Ryder & Seno ft. El Nikko -Mami (TeaMix 9 - Sagiv Alfasi Redrum Edit)\n"
    + "The Ultras Ft. Noa Kirel - Cinderella (TeaMix 9 - RooBen Edit)\n"
    + "Timmy Trumpet, Lady Bee - Trumpets (TeaMix 9 - RooBen Intro)\n"
    + "Travis Scott ft Drake - Sicko Mode (TeaMix 9 - RooBen Intro Edit) (Drake Only)\n"
    + "עומר אדם - רחוק מכולם (TeaMix 9 - Dudu A'S Edit)\n"
    + "עומר אדם - רחוק מכולם (TeaMix 9 - RooBen Redrum) (Intro) 60\n"
    + "עומר אדם - רחוק מכולם (TeaMix 9 - RooBen Redrum) 60\n";

  private teamixVol10 =
    "Andrea Damante ft. Rich The kid & Ray J - Rub It (TeaMix 10 - DJ Kuper Intro) (ShortCut)\n"
    + "Anuel AA - Quiere Beber (TeaMix 10 - RooBen Redrum)\n"
    + "Anuel AA ft Zion - Hipocrita (TeaMix 10 - RooBen Redrum)\n"
    + "Bad Bunny feat. Drake - Mia (TeaMix 10 - IdoM Intro Edit)\n"
    + "Bad Bunny feat. Drake - Mia (TeaMix 10 - RooBen Transition Redrum) 80-100\n"
    + "Chyno Miranda ft J Balvin - El Peor (TeaMix 10 - RooBen Redrum)\n"
    + "Drake Ft. Giggs - KMT (TeaMix 10 - RooBen Intro)\n"
    + "Future and Juice WRLD feat Nicki Minaj - Transformer (TeaMix 10 - RooBen Intro)\n"
    + "Future and Juice WRLD feat Nicki Minaj - Transformer (TeaMix 10 - RooBen Transition) 100-78.5\n"
    + "Future Ft. Juice WRLD - Fine China (TeaMix 10 - RooBen Intro Transition) 100-83\n"
    + "Future Ft. Juice WRLD - Fine China (TeaMix 10 - RooBen Intro)\n"
    + "Kodak Black ft Travis Scott & Offset - ZEZE (TeaMix 10 - DJ Kuper Intro)\n"
    + "Lil Pump ft Lil Uzi Vert - Multi Millionaire (TeaMix 10 - RooBen Redrum)\n"
    + "Lil Pump ft Lil Uzi Vert - Multi Millionaire (TeaMix 10 - RooBen Transition Redrum) 100-73\n"
    + "Lil Wayne - Uproar (TeaMix 10 - DJ Kuper Intro)\n"
    + "MC Kekel e MC Rita - Amor de Verdade (TeaMix 10 - RooBen Redrum)\n"
    + "Nicky Jam Ft. Steve Aoki - Jaleo (TeaMix 10 - Dudu A'S Redrum)\n"
    + "Ozuna Ft. Akon - Comentale (TeaMix 10 - Dudu A'S Redrum)\n"
    + "Rihanna  Jay-Z - Umbrella Gama x Noisey Boys (TeaMix 10 - IdoM Edit)\n"
    + "Stefflon Don - Crunch Time (TeaMix 10 - DJ Kuper Intro)\n"
    + "Wiz Khalifa ft. Lil Skies - Fr Fr (TeaMix 10 - DJ Kuper Intro)\n"
    + "גיל ויין - ככה לומדים להעריך (TeaMix 10 - Dudu A'S Redrum)\n"
    + "דוד פארוק - חגורה שחורה (TeaMix 10 - RooBen Intro)\n"
    + "סטפן לגר - מרסי (TeaMix 10 - RooBen Redrum)\n"
    + "עדן בן זקן - מקסיקו (TeaMix 10 - RooBen Reggaeton Edit)\n"
    + "עדן חסון - מתפוצץ לי הראש (TeaMix 10 - Dudu A'S Redrum)\n"
    + "רינת בר & חיילי הנקמה - אחת מאלף (TeaMix 10 - Dudu A'S & RooBen Redrum)\n";

  private teamixVol11 =
    "6ix9ine ft. Tory Lanez - KIKA (TeaMix 11 - DJ Kuper Intro)\n"
    + "Alex Mica feat. D.E.P. & Kalif - Latina loca (TeaMix 11 - RooBen Intro)\n"
    + "Arabian Trap - Bad Boy (TeaMix 11 - Saqiv Alfasi Redrum)\n"
    + "Arabian trap X ATC - Bad Boy Around The World (TeaMix 11 - Saqiv Alfasi Mashup)\n"
    + "Aya Nakamura - Djadja (TeaMix 11 - RooBen Mashup)\n"
    + "Bebe Rexha - I'm a Mess (TeaMix 11 - RooBen Reggaeton Edit)\n"
    + "Caza & Famke Louise - Slide (TeaMix 11 - RooBen Redrum)\n"
    + "DaniLeigh Ft. Lil Baby - Lil Bebe (Remix) (TeaMix 11 - DJ Kuper Intro)\n"
    + "DDG ft YBN Nahmir, G Herbo & Blac Youngsta - Run It Up (TeaMix 11 - DJ Kuper Intro)\n"
    + "D-Lo ft. Tyga - Get Her Tho (TeaMix 11 - DJ Kuper Intro)\n"
    + "Dua Lipa, BLACKPINK - Kiss and Make Up (TeaMix 11 - RooBen Intro)\n"
    + "Kelly Rowland - Kelly (TeaMix 11 - DJ Kuper Intro)\n"
    + "Kris Kross Amsterdam X Ally Brooke X Messiah - Vamonos (TeaMix 11 - Sagiv Alfasi Redrum)\n"
    + "Lukas Graham - Love Someone (TeaMix 11 - RooBen Redrum)\n"
    + "Nicki Minaj - Barbie Tingz (TeaMix 11 - DJ Kuper Edit)\n"
    + "Pardison Fontaine ft Cardi B - Backin It Up (TeaMix 11 - Dj Sagiv Alfasi Intro)\n"
    + "Travis Scott ft. Kendrick Lamar - Goosebumps (TeaMix 11 - DJ Kuper Intro)\n"
    + "Travis Scott ft. Kendrick Lamar - Goosebumps (TeaMix 11 - DJ Kuper Transition) 100-65\n"
    + "Tyga ft. Nicki Minaj - Dip (TeaMix 11 - Sagiv Alfasi Intro)\n"
    + "XXXTENTACION - Look At Me (TeaMix 11 - DJ Kuper Intro)\n"
    + "טאליסמן - זנזיבר (TeaMix 11 - Dudu A'S Juju Intro)\n"
    + "נתי - מחרוזת שירי חנוכה (TeaMix 11 - Dudu A'S Redrum)\n"
    + "עומר אדם, מארינה מקסימליאן, נדב גדג' ומה קשור - לרקוד ולזוז (TeaMix 11 - RooBen Edit) 105 -134\n"
    + "עומר אדם, מארינה מקסימליאן, נדב גדג' ומה קשור - לרקוד ולזוז (TeaMix 11 - RooBen Edit) 105\n"
    + "רגב הוד - אחרי כל הסופות (TeaMix 11 - Dudu A'S Redrum)\n";

  private teamixVol12 =
    "Ciara - Level Up (DJ Kuper 'Fuck It Up Edit) 153\n"
    + "Clean Bandit - Solo (Aviel Mymon Edit) 105\n"
    + "DaniLeigh ft YBN Nahmir & YG - Can't Relate (RooBen Intro) 80\n"
    + "Drake - Keke (DJ Kuper 'Do You Love Me' Edit) 70-95\n"
    + "Flipp Dinero - Leave Me Alone (RooBen Intro) 75\n"
    + "Hardwell ft Conor Maynard & Snoop Dogg - How You Love Me (RooBen Intro) 105\n"
    + "Ilkay Sencan - Do It (Syco Fix) 108\n"
    + "Jason Derulo & David Guetta ft Nicki Minaj & Willy William - Goodbye (DJ Kuper Intro) 103\n"
    + "Kojo Funds - Check (feat. RAYE) (DJ Kuper Intro) 94\n"
    + "Marwa Loud - Billet (RooBen Intro) 97\n"
    + "Massari Feat. Raja Kumari - Miss Fatty (Buskilaz Remix - Aviel Mymon Fix) 100\n"
    + "Pitbull ft Rhea - Ocean To Ocean (RooBen Intro) 105\n"
    + "Post Malone - Wow (Aviel Mymon Intro) 100\n"
    + "Quavo - WORKINME (DJ Kuper 'Lil Jon Energy' Transition) 85-75\n"
    + "Rich The Kid - Splashin (DJ Kuper Intro) 100\n"
    + "Saweetie - Pissed (RooBen Intro) 93\n"
    + "Sheck Wes - Mo Bamba (Aviel Mymon Intro) 73\n"
    + "Sneakk ft Tyga & YG - Spray (RooBen Intro) 96\n"
    + "T-Jones - Ali (RooBen Intro) 77.5\n"
    + "YFN Lucci & Rich Homie Quan ft Garren - Live That Life (RooBen Intro) 73\n"
    + "YFN Lucci & Rich Homie Quan ft Garren - Live That Life (RooBen Transition) 100-73\n"
    + "YFN Lucci ft Rich The Kid - Double Up (RooBen Intro) 71\n"
    + "אייל גולן - טירוף מתוק (RooBen Reggaeton Edit) 105\n"
    + "טליסמאן - דור ה YY (Syco Fix) 132\n"
    + "עומר אדם, מארינה מקסימליאן, נדב גדג' ומה קשור - לרקוד ולזוז (Syco Fix) 94 - 120\n";

  private teamixVol13 =
    "A Boogie Wit Da Hoodie - Look Back At It (RooBen Intro)\n"
    + "Aya Nakamura - La Dot (RooBen Redrum)\n"
    + "Beyonce & Jay-Z - Apesh#T (Nasa Redrum) (DJ Kuper Fix)\n"
    + "Ciara - Level Up (Roman Kuper Intro)\n"
    + "DJ Spinking ft. Tyga, A$ap Ferg, Jeremih, Velous - Adult Swim (DJ Kuper Edit) V3\n"
    + "Dua Lipa & Blackpink - Kiss And Make Up (Dudu A'S Redrum)\n"
    + "Jidenna ft. Roman Gianarthur - Classic Man (DJ Kuper Intro)\n"
    + "Jonn Hart ft Too Short & Juelz Santana - Whistle (DJ Kuper Intro)\n"
    + "Kid Ink ft. Dej Loaf - Be Real (DJ Kuper Intro)\n"
    + "Kid Ink, Lil Wayne, Saweetie - YUSO (DJ Kuper Intro)\n"
    + "Kid Ink, Rich The Kid - No Budget (DJ Kuper Intro)\n"
    + "Lil Pump - Butterfly Doors (Syco Intro)\n"
    + "Migos - Fight Night (DJ Kuper Intro)\n"
    + "Nicki Minaj & Anuel AA FT. Bantu - Familia (DJ Kuper Intro)\n"
    + "Sheck Wes - Mo Bamba (DJ Kuper Intro)\n"
    + "Starboy feat. Wizkid, Ceeza Milli, Spotless & Terri - Soco (DJ Kuper Intro)\n"
    + "Sting vs. Craig David - Rise & Fall Of My Heart (DJ Kuper 'Wedding' Edit)\n"
    + "Tony T, Alba Kras & Gal Malka - Jiggy Jiggy (Dudu A'S Redrum)\n"
    + "Travis Porter ft. Tyga - Ayy Ladies (DJ Kuper Edit)\n"
    + "Tyga ft. Offset - Taste (DJ Kuper ShortCut) v3\n"
    + "Vegedream - Ramenez La Coupe (Buskilaz Remix - RooBen Fix)\n"
    + "אודימן ,עידו בי וצוקי - קקדו (Dudu A'S Redrum)\n"
    + "מושיקו מור - טיפוס של חורף (Dudu A'S Redrum)\n"
    + "סטטיק ובן אל תבורי עם עדן בן זקן וסטפן לגר - יאסו (Dudu A'S Redrum)\n"
    + "סטטיק ובן אל תבורי עם עדן בן זקן וסטפן לגר - יאסו (RooBen Redrum)\n"
    + "צגאי בוי - ג׳וסי (אווו) (Syco Intro)\n"
    + "צגאי בוי - האשטאג מוד (Syco Intro) V1\n"
    + "צגאי בוי - האשטאג מוד (Syco Intro) V2\n";

  private teamixVol14 =
    "6ix9ine ft. Tory Lanez - KIKA (DJ Kuper Intro) (V2)\n"
    + "Andrey Exx, Pushkarev feat. Stromae - Keep the ALORS ON DANSE (IdoM Mashup)\n"
    + "Ariana Grande - 7 Rings (RooBen Redrum)\n"
    + "Artbat - Upperground (Dudu A'S Edit)\n"
    + "Blueface ft YG - Thotiana (RooBen Intro)\n"
    + "Busta Rhymes - Touch It (Kuper Edit)\n"
    + "Coeus - Solar (DJ Kuper Short Edit) (V2)\n"
    + "DaR & DoR - Going Nowhere (DJ Kuper Edit)\n"
    + "Dynoro & Gigi D'Agostino - In My Mind (German Avny & Mike Tsoff Remix - IdoM EDIT)\n"
    + "Eden Hason - Hey DJ (Syco Intro)\n"
    + "Ella Mai - Trip (XMiX Remix) (DJ Kuper Fix)\n"
    + "Fisher - Losing It America (Dudu A'S Short Edit)\n"
    + "Future - Stick to the Models (Syco Intro)\n"
    + "G-Eazy ft. Yo Gotti & YBN Nahmir - 1942 (Syco Intro)\n"
    + "Ghoss - Cut Up (RooBen Intro)\n"
    + "Kris Kross Amsterdam X Ally Brooke X Messiah - Vamonos (Sagiv Alfasi Redrum - Syco Hook 1st)\n"
    + "Lil Pump ft Lil Wayne - Be Like Me (RooBen Intro)\n"
    + "Lil Pump ft Lil Wayne - Be Like Me (RooBen Transition) 80-104\n"
    + "Meek Mill ft. Cardi B - On Me (DJ Kuper Transition) 100-66\n"
    + "Natti Natasha - Toca Toca (RooBen Intro)\n"
    + "Nicki Minaj & Anuel AA FT. Bantu - Familia (DJ Kuper Intro)\n"
    + "O.T. Genasis - Bae (Syco Intro)\n"
    + "Raja Kumari - Shook (RooBen Intro)\n"
    + "Rauf & Faik - детство (Rakurs & Eddie G Remix - Syco Fix)\n"
    + "Sak Noel & Lil Jon - Demasiado Loca (RooBen Intro)\n"
    + "Sneakk ft Tyga & YG - Spray (DJ Kuper Intro)\n"
    + "Stylo - Indian Spirit (IdoM Edit)\n"
    + "Wiley, Stefflon Don & Sean Paul ft Idris Elba - Boasty (RooBen Intro)\n"
    + "Wiley, Stefflon Don & Sean Paul FT. Idris Elba - Boasty (DJ Kuper Intro)\n"
    + "אופק אדנק - עושים ת'בלאגן (RooBen Intro)\n"
    + "אופק אדנק - עושים ת'בלאגן (RooBen Transition) 100-82\n"
    + "מרגי Mergui - הזוג הזה (IdoM Intro)\n"
    + "נועה קירל - דראם (Dudu A'S Redrum)\n"
    + "סטטיק ובן אל תבורי & עדן בן זקן - יאסו (Syco Intro)\n"
    + "עדן חסון - היי די.ג'יי (RooBen Redrum) Fix\n"
    + "עומר אדם - חברות שלך 1+2 (RooBen Transition) 100-110\n"
    + "עומר אדם - חברות שלך 2 (IdoM Intro)\n"
    + "עומר אדם - חברות שלך 2 (RooBen Intro) Hook 1st\n"
    + "עומר אדם - חברות שלך 2 (RooBen Intro)\n"
    + "עידן רייכל & טריפל - ואם תבואי אליי (Danny Gitelss Shape Edit - Syco Fix) V1\n"
    + "עידן רייכל & טריפל - ואם תבואי אליי (Danny Gitelss Shape Edit - Syco Fix) V2\n"
    + "רון נשר עידו ונה ובן קיסר - דייט עם תימני (Dudu A'S Redrum)\n";

  private teamixVol15 =
    "Armin van Buuren - Turn It Up (Aviel Mymon Fix)\n"
    + "ARTBAT - Upperground (Aviel Mymon Fix)\n"
    + "Agnez Mo ft. Chris Brown & Juicy J - Overdose (TSD Remix - DJ Kuper Edit)\n"
    + "Ardian Bujupi Ft. Farruko y Xhensila - Cika Cika (RooBen Intro)\n"
    + "Ariana Grande - 7 Rings (Robert Cristian Remix - Dudu A'S Edit)\n"
    + "ATB X Roei Malka - 9PM (RooBen Mashup)\n"
    + "Bolier, Trobi - In The Water (Sagiv Alfasi Edit)\n"
    + "Camila Cabello - Havana (Sagi Kariv Remix - Dudu A'S Edit)\n"
    + "Carlos Vives Ft. Wisin - Si Me Das Tu Amor (RooBen Intro) Hook 1st\n"
    + "Carlos Vives Ft. Wisin - Si Me Das Tu Amor (RooBen Intro)\n"
    + "Clean Bandit feat. Ellie Goulding - Mama (Syco Edit) V1\n"
    + "Clean Bandit feat. Ellie Goulding - Mama (Syco Edit) V2\n"
    + "Confieso - F4ST (Sagiv Alfasi Edit)\n"
    + "Diplo - Oh Maria (Syco Intro)\n"
    + "Drake - One Dance (Moshe Buskila - Dudu A'S Intro)\n"
    + "Eleni Foureira - Fuego (DJ Kuper Edit)\n"
    + "German Avny & Mike Tsoff - Believe (Extended Mix)\n"
    + "German Avny & Mike Tsoff - Believe (Radio Mix)\n"
    + "Hellm8 vs. SMVGGLERS - Freedom (Sagiv Alfasi Short Edit)\n"
    + "?Insideeus - Bubble On Me (RooBen Intro)\n"
    + "J Balvin - Ay Vamos (RooBen Redrum)\n"
    + "Jenia & Jinga & Sagi Kariv - TakaDoom (RooBen Mashup)\n"
    + "Krept & Konan ft Jeremih - Freak Of The Week (DJ Kuper Intro)\n"
    + "Lady Gaga Ft. Bradley Cooper - Shallow (Nesco Remix - A'S Edit)\n"
    + "Maluma - HP (RooBen Intro)\n"
    + "Marwa Loud - Bad Boy (DJ Kuper Edit)\n"
    + "Migos ft. Lil Uzi Vert - Bad And Boujee (DJ Kuper Transition) 80-63\n"
    + "Nacho - Nadie Sabe (RooBen Intro)\n"
    + "Nicky Jam Ft. Ozuna - Te Robare (RooBen Redrum)\n"
    + "Offer Nissim - Esther (Dudu A'S Edit)\n"
    + "Ozuna Feat. Akon - Coméntale (Aviel Mymon Intro)\n"
    + "Rauf & Faik - Детство (Rakurs & Eddie G Remix - Syco Fix)\n"
    + "Shakedown - At Night (Purple Disco Machine Extended Remix - IdoM Edit)\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V1\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V2\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V3\n"
    + "Sllash & Doppe - Aguella (Aviel Mymon Fix)\n"
    + "Technotronic - Pump Up The Jam 19 (Sergey Kutsuev Remix - Dudu A'S Edit) 125 BPM\n"
    + "The Weeknd - I Cant Feel My Face (DJ Kuper Transition) 125-108\n"
    + "Tropkillaz Ft. J Balvin, Anitta y MC Zaac - Bola Rebola (RooBen Intro)\n"
    + "The Prince Karma - Later Bitches (Aviel Mymon Intro)\n"
    + "Tyga - Rack City (DJ Kuper Edit)\n"
    + "Wyclef Jean & Missy Elliott - Party To Damascus (DJ Kuper Intro)\n"
    + "אייל גולן - הפוך מהיקום (Dudu A'S Redrum)\n"
    + "אייל גולן ועופר ניסים - לא מבינה עברית (Guy Raz Remix - Dudu A'S Edit)\n"
    + "אניה בוקשטיין ועופר ניסים - רוקדת (RooBen Fix)\n"
    + "דודו אהרון - הלב שלי על מאתיים (RooBen Mashup) V2\n"
    + "דודו אהרון - הלב שלי על מאתיים (RooBen Mashup) V3\n"
    + "עדן בן זקן - תגיד לי (RooBen Mashup)\n"
    + "עומר אדם - תגידי לי שטוב לך (BlazE & Matan Amar Remix - RooBen Short Edit)\n"
    + "עדן חסון - שיכורים (Mor David X Yonatan Harlev - Aviel Mymon Fix)\n";

  private teamixVol16 =
    "4 Strings vs. Sick Inviduals & Holl & Rush - Take Me Away (German Avny Mashup)\n"
    + "Age Of Love - The Age Of Love (Solomun Renaissance - Gidi Assayag Edit)\n"
    + "Age Of Wena Paradise (Gavri Blend X Or Pilo - Aviel Mymon Intro Edit)\n"
    + "Alan Walker, Sabrina Carpenter & Farruko - On My Way (Mike Tsoff & German Avny Remix)\n"
    + "Arm In Arm - Hunger For Your Vibe (Moonwalk Remix - Gidi Assayag Edit)\n"
    + "ARTBAT - Upperground (Gidi Assayag Edit)\n"
    + "Avicii ft Aloe Blacc - SOS (RooBen Intro)\n"
    + "Chris Brown ft. Nicki Minaj & G-Eazy - Wobble Up (DJ Kuper Intro)\n"
    + "City Girls - Act Up (RooBen Intro)\n"
    + "Cola X Trance 7 (Aviel Mymon Power Edit)\n"
    + "Dennis Lloyd - Never Go Back (RooBen Private Redrum)\n"
    + "Duke Dumont - Red Light Green Light (IdoM Edit)\n"
    + "Eleni Foureira - Fuego (DJ Kuper Edit)\n"
    + "Infected Mushroom, WARRIORS vs. Rozalla - Becoming Insane (German Avny Mashup)\n"
    + "Jayh - Fluister (RooBen Edit)\n"
    + "Loni - Loneliness (Gidi Assayag Edit)\n"
    + "Madonna Ft. Maluma - Medellín (RooBen Redrum)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (DJ Kuper Intro)\n"
    + "Natti Natasha Y Anitta - Te Lo Dije (RooBen Intro)\n"
    + "Niels Van Gogh - Pulverturm (Tiesto Remix - Gidi Assayag Edit)\n"
    + "Offer Nissim - Alone (German Avny Mashup)\n"
    + "Post Malone & Swae Lee - Sunflower (Panic City Remix - DJ Kuper Fix)\n"
    + "Rej3ctz - Baby Shark (Twerk Remix - Tommy K. & DJ Kuper Edit)\n"
    + "Sagiv Alfasi - Independence Day (Israel VS Dana)\n"
    + "Saturator X עומר אדם -יעשו לנו כבוד (Sagiv Alfasi Mashup)\n"
    + "Space Motion - Epic (Gidi Assayag Edit)\n"
    + "ToMix & Genish - Lam Gana Poo (RooBen Fix)\n"
    + "Tyga - Goddamn (RooBen Intro)\n"
    + "Warp brothers and Aquagen vs. Alexx Slam - Blade (German Avny Mashup)\n"
    + "Zivert - Life (German Avny & Mike Tsoff Remix)\n"
    + "אייל גולן - לרקוד כמו משוגע (Daniel Remix - Dudu A'S Edit)\n"
    + "אייל גולן - שיכור בלילות (Dudu A'S Darbuka Remix)\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - RooBen Fix)\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - Syco Edit) V2\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - Syco Edit)\n"
    + "אייל גולן X Vivo - לרקוד כמו משוגע (Daniel Remix - Aviel Mymon Fix)\n"
    + "איתי לוי - קעקוע על הלב (Daniel Remix - Aviel Mymon Fix)\n"
    + "יעל מאס מארחת את צגאי בוי - גודטיים (RooBen Intro)\n"
    + "מושיקו מור - תסביכים (Kobi Shaltiel Remix - Syco Fix) V1\n"
    + "מושיקו מור - תסביכים (Kobi Shaltiel Remix - Syco Fix) V2\n"
    + "מירי מסיקה - מפחד עלייך (DANIELRemix - RooBen Fix)\n"
    + "משה פרץ - מתי (Dudu A'S Redrum)\n"
    + "נוי פדלון - מפחיד (IdoM & Roby Fayer Intro)\n"
    + "נוי פדלון - מפחיד (RooBen Intro) Hook 1st\n"
    + "נתן גושן - מתגעגעת (Dudu A'S Redrum)\n"
    + "סטפן לגר ואופק המלאך - יום הולדת (RooBen Intro)\n"
    + "עומר אדם - יעשו לנו כבוד (Gidi Assayag Remix)\n"
    + "עומר אדם - יעשו לנו כבוד (Mor David Remix - Syco Fix)\n"
    + "צפריר יפרח וסמואל שובל - דרבוקה (Dudu A'S Long Edit)\n"
    + "צפריר יפרח וסמואל שובל - דרבוקה (Dudu A'S Short Edit)\n"
    + "שרית חדד ועופר ניסים - SHUFUNI (Aviel Mymon Intro)\n";

  private teamixVol17 =
    "Alan Walker, Sabrina Carpenter & Farruko - On My Way (RooBen Redrum) 97\n"
    + "Alex Guesta - Akachi (Sagiv Alfasi Edit )\n"
    + "Ava Max - Sweet But Psycho (Dark & Adrian - Dudu A'S Edit)\n"
    + "Backstreet Boys X Krajno - I Want It In Anatolia Way (Skeletron - IdoM Edit)\n"
    + "Blastoyz, Reality Test - Kabalah (Sagiv Alfasi Edit)\n"
    + "Corinda, AfroTura - Aso (RooBen Fix)\n"
    + "Daddy Yankee x Balkan Beat Box - Shaky Shaky (IdoM Edit)\n"
    + "Daniel Portman - Casa Rumba (Sagiv Alfasi Edit)\n"
    + "Dimitri Vegas, Like Mike, Liquid Soul, Vini Vici - Untz Untz (Sagiv Alfasi Edit)\n"
    + "DJ Snake Ft. Selena , Cardi B & Ozuna - Taki Taki (Sharon Yosefov - A'S Intro)\n"
    + "DJ Snake x Ozuna x Cardi B x Lowderz & Zuffo - Taki Taki Blend (IdoM EDIT) 125-100\n"
    + "Dor Mor - Clock (Gidi Assayag Edit)\n"
    + "Dua Lipa X Thomas Gold - One Kiss Orinoco (Aviel Mymon Mashup)\n"
    + "Ed Sheeran & Justin Bieber - I Don't Care (RooBen Redrum)\n"
    + "French Montana ft. Blueface & Lil Tjay - Slide (DJ Kuper Intro)\n"
    + "Gigi D'Agostino - In My Mind (German Avny & Mike Tsoff - Gidi Assayag Edit)\n"
    + "Hechizeros Band vs DJ Willie - El Sonidito (Make Some Noise Bootleg - Gidi Assayag Edit)\n"
    + "Kanye West & Lil Pump Vs. The Kemist & Braindead Ft. Nyanda - I Love It (Dudu A'S Fix)\n"
    + "KAZKA - Cry (R3HAB Remix - RooBen Power Edit)\n"
    + "Loni - Loneliness (Sagiv Alfasi Edit )\n"
    + "Losless - Synecku - (Gidi Assayag Long Edit)\n"
    + "Losless - Synecku - (Gidi Assayag Short Edit)\n"
    + "Luca Hanni - She Got Me (RooBen Redrum) Eurovision 2019\n"
    + "Lunay Ft Daddy Yankee & Bad Bunny - Soltera (RooBen Intro)\n"
    + "Mahmood - Soldi (Denis First - Dudu A'S Edit)\n"
    + "Mahmood - Soldi (Denis First Remix - Gidi Assayag Edit)\n"
    + "Mahmood - Soldi (Syco Intro)\n"
    + "Maitre Gims ft. Maluma - Hola Senorita (RooBen Redrum\n"
    + "Mann ft. 50 Cent - Buzzin (Remix) (DJ Kuper Edit)\n"
    + "Marshmello, Chris Brown, Tyga - Light It Up (DALI Intro)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (DJ Kuper Intro)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (Gidi Assayag Acapella Out Edit)\n"
    + "Meek Mill ft. Ella Mai - 24_7 (DJ Kuper Intro)\n"
    + "Monolink - Return to Oz (Artbat Remix - Gidi Assayag Long Edit)\n"
    + "Monolink - Return to Oz (Artbat Remix - Gidi Assayag Short Edit)\n"
    + "Moonwalk - Galactic (Stil Vor Talent Remix - Aviel Mymon Edit)\n"
    + "Netta VS Lil Jon - Bassa Mind (Sagi Atia & ShPiz Intro - Aviel Mymon Edit)\n"
    + "Olivier Giacomotto - Bipolar Star (Victor Ruiz Remix - Aviel Mymon Fix)\n"
    + "OT Genasis - Bae (DJ Kuper Transition) 80-101\n"
    + "Panic! At The Disco - High Hopes (RooBen Private Mashup)\n"
    + "Tokyo Drift X Tempera (Aviel Mymon Edit)\n"
    + "Trance Wax & Omer Adam - Trance 7 (DJ Kuper 'Tagidi Li She Tov' Edit)\n"
    + "Tyga - Goddamn (DALI Intro) V1\n"
    + "Tyga - Goddamn (DALI Intro) V2\n"
    + "WW x Vini Vici - SHAMELESS Chakra (MANI - IdoM Edit)\n"
    + "Zedd, Katy Perry - 365 (German Avny & Mike Tsoff Remix)\n"
    + "ZENA - Like It (RooBen Redrum) Eurovision 2019\n"
    + "מושיקו מור - הניחי לי (RooBen Intro Redrum)\n"
    + "מושיקו מור - הניחי לי (RooBen Redrum)\n"
    + "עדן חסון - כפיות (Mor David Remix - IdoM Edit)\n"
    + "עומר אדם - יעשו לנו כבוד (Shon Hen Remix - Aviel Mymon Edit)\n"
    + "פאר טסי - מי אני (Dudu A'S Redrum)\n";

  private teamixVol18 =
    "Exclusive :\n"
    + "\n"
    + "Chen Leiba - Leibailar (Shon Hen Official Remix).wav\n"
    + "Chen Leiba - Leibailar (Shon Hen Remix - RooBen Fix).mp3\n"
    + "Chen Leiba Ft.Tomer Aaron - Mabruk Alekha (Original Mix).mp3\n"
    + "Chen Leiba, Chen Mantsoor, Sivan - Electrafied (Extended).mp3\n"
    + "Eli Arbiv, Chen Leiba - Nothing's Stopping Me (Extended).mp3\n"
    + "German Avny - Gaya (Extended Mix).mp3\n"
    + "German Avny - Gaya (Original Mix).mp3\n"
    + "\n"
    + "Hip Hop - Dancehall - Pop :\n"
    + "\n"
    + "Charly Black X Nicky Jam & J Balvin X RooBen - Party X (Aviel Mymon Edit).mp3\n"
    + "Kamaiyah ft. Tyga & Quavo - Windows (DJ Kuper Transition) (Tyga First) 80-100.mp3\n"
    + "Kanye West Lil Pump X Usher - I Love it Yeah (Sagiv Alfasi Break Mash-up).mp3\n"
    + "King Deco X Sean Paul - Castaway (Don't Leave Me) (RooBen Edit).mp3\n"
    + "Lil Nas X - Old Town Road (DJ Kuper Aca In).mp3\n"
    + "Lil Nas X - Old Town Road (RooBen Redrum) Acapella In.mp3\n"
    + "Meek Mill ft. Ella Mai - 24_7 (DJ Kuper Intro).mp3\n"
    + "Nicki Minaj X Mr Vegas - Megatron (RooBen Edit).mp3\n"
    + "OT Genasis - Bae (DJ Kuper Transition) 80-101.mp3\n"
    + "Starboy - Soco (DJ Kuper Aca In).mp3\n"
    + "Tyga ft. J Balvin & Chris Brown - Haute (DJ Kuper Intro).mp3\n"
    + "Young Thug ft. J. Cole & Travis Scott - The London (DJ Kuper Transition) 75-98.mp3\n"
    + "\n"
    + "Reggaeton :\n"
    + "\n"
    + "Borja Rubio Y Juan Magan - Y Si Te Beso, Que (RooBen Intro) Hook 1st.mp3\n"
    + "Borja Rubio Y Juan Magan - Y Si Te Beso, Que (RooBen Intro).mp3\n"
    + "Jhay Cortez, J Balvin Y Bad Bunny - No Me Conoce (RooBen Intro) Hook 1st.mp3\n"
    + "Maluma - HP (Mor David Remix - Itay Ben Senyor Fix).mp3\n"
    + "Taki Taki X הניחי לי (Or Pilo Mashup - Itay Ben Senyor Fix).mp3\n"
    + "\n"
    + "Techno - Electo House - Mashup :\n"
    + "\n"
    + "Age Of Love - The Age Of Love (Solomun Renaissance - Gidi Assayag Edit).mp3\n"
    + "Alex Guesta, Benzly Hype, Raphael - Dance 4 Me (Paul Jockey Remix - Sagiv Alfasi Edit).mp3\n"
    + "Bipolar Star (Victor Ruiz Remix - Itay Ben Senyor Fix).mp3\n"
    + "El Mundo Zazou - Can You See What I See Elfenberg Remix (Sagiv Alfasi Edit).mp3\n"
    + "Evokings - On The Floor (Aviel Mymon Fix).wav\n"
    + "Extinct X Jax Jones - Lose Yourself (Jonni M Mashup - Aviel Mymon ReWork Edit).mp3\n"
    + "Gettoblaster - Future Funk (Itay Ben Senyor Fix).mp3\n"
    + "Hardwell & Franky Rizardo - Asteroid (Aviel Mymon Edit).mp3\n"
    + "Jako Vs Work (Ofek Yom Tov & Roie Malka Mash - Itay Ben Senyor Fix).mp3\n"
    + "Jenia & Jinga - Takadoom (Lidor Zirk Remix - Itay Ben Senyor Edit).mp3\n"
    + "Komodo - (I Just) Died In Your Arms (German Avny & Mike Tsoff Remix).mp3\n"
    + "K£ra - Gogo (Nathan Thomson Remix - Itay Ben Senyor Fix).mp3\n"
    + "Layton Giordani - Drumcode (Itay Ben Senyor Fix).mp3\n"
    + "Meduza ft. Goodboys - Piece Of Your Heart (Syco Edit).mp3\n"
    + "Sunnery James Ryan Marciano - Yeke Yeke (Sagiv Alfasi Avira Edit).mp3\n"
    + "Timmy Trumpet x Cardi B - I Like Al Pacino (Aviel Mymon Mashup).mp3\n"
    + "Zafrir Ifrach - Mama Daili ft. Naj (Syco Extended).mp3\n"
    + "\n"
    + "ישראלי - מזרחי - דאנס :\n"
    + "\n"
    + "Ido Shoam & Hovevi Tzion - Rotze Banot (Syco Edit).mp3\n"
    + "Mor Avrahami ft Izhar Cohen - Abanibi (Sagiv Alfasi Edit).mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V1.mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V2.mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V3.mp3\n"
    + "Stephane Legar - Kapara (Rotem Baum Rmx - Syco Edit) V1.mp3\n"
    + "Stephane Legar - Kapara (Rotem Baum Rmx - Syco Edit) V2.mp3\n"
    + "אגם בוחבוט - בננות (RooBen Redrum)\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro) Acapella In\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro) Hook 1st\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro)\n"
    + "אייל גולן - אוסף עוד געגוע (Dudu A'S Redrum)\n"
    + "אייל גולן ובניה ברבי - ממה את מפחדת (Eli Arbiv Intro Remix - Itay Ben Senyor Fix)\n"
    + "אייל גולן ובניה ברבי - ממה את מפחדת (Eli Arbiv Remix - Itay Ben Senyor Fix)\n"
    + "איתי לוי - קעקוע על הלב (DANIEL Remix - Itay Ben Senyor Fix)\n"
    + "אליעד - מסע (Dudu A'S Redrum)\n"
    + "אליעד - מסע (Sharon Yosefov - Dudu A'S No Drop Edit)\n"
    + "אליעד - מסע (Yosefov Remix - Itay Ben Senyor Fix) V2\n"
    + "אליעד - מסע (Yosefov Remix - Itay Ben Senyor Fix)\n"
    + "גל מלכה & אקסום & אבי היילו - לה לה (RooBen Private Edit)\n"
    + "דודו אהרון ואיתי לוי - השמחה שלנו (Sharon Yosefov Remix - Itay Ben Senyor Fix)\n"
    + "נועה קירל - חצוף (RooBen Edit)\n"
    + "סטטיק ובן אל תבורי - בננות (Dudu A'S Redrum)\n"
    + "עדן בן זקן - תגיד לי (Yohan Cohen Remix - Itay Ben Senyor Fix)\n"
    + "עדן בן זקן & עדן חסון - שונה מהנוף (Dudu A'S Redrum)\n"
    + "עדן בן זקן & עדן חסון - שונה מהנוף (RooBen Redrum)\n"
    + "עדן חסון - איך את אוהבת (Mor David Remix - Itay Ben Senyor Fix)\n"
    + "עדן חסון - אין יותר מועדונים (Alon Mix & Yaki - E Remix - Itay Ben Senyor Fix)\n"
    + "עומר אדם - טמפרטורה (Dudu A'S Redrum)\n"
    + "עומר אדם - יעשו לנו כבוד (RooBen Private Mashup)\n"
    + "עומר אדם - תתן לה פרחים (Dudu A'S Redrum)\n"
    + "עומר-אדם - לרקוד ולזוז (Sharon Yosefov Remix - Sagiv Alfasi Edit) 105-128\n";

  private teamixVol19 = "Exclusive :\n"
    + "\n"
    + "Arthur Project - Akabee [Original Mix].mp3\n"
    + "Arthur Project - Akabee [Radio Mix].mp3\n"
    + "Arthur Project - Akabee [Radio Vocal Mix].mp3\n"
    + "Arthur Project - Akabee [Vocal Mix].mp3\n"
    + "Arthur Project - Touch and press Play (Extended Version).mp3\n"
    + "Arthur Project - Touch and press Play.mp3\n"
    + "Denis First & Reznikov & Bright Sparks - Shameless (Mike Tsoff & German Avny Remix).mp3\n"
    + "Fetty Wap ft Nicki Minaj - Like A Star (RooBen Remix).mp3\n"
    + "Jax Jones, Martin Solveig, Madison Beer - All Day And Night (German Avny & Mike Tsoff Remix).mp3\n"
    + "Mahmood - Soldi (Aviel Mymon Transition) 100 - 128.mp3\n"
    + "Netta X Bad Bunny, Ozuna, Nicky Jam - BassaBote (Aviel Mymon Edit) V2.mp3\n"
    + "\n"
    + "Hip Hop - Dancehall - Pop :\n"
    + "\n"
    + "Atomic - Te De Campana (Buskilaz Remix - Syco Fix).mp3\n"
    + "Balkan Beat Box & DJ Tokuc feat. Tommy Gunz  - Hermetico Saxophone (Aviel Mymon Brake Edit).mp3\n"
    + "BrainDeaD - Boom Shakalarma (Aviel Mymon Intro Edit).mp3\n"
    + "DJ Snake X Lauv - A Different Way Magenta (Aviel Mymon Mashup).mp3\n"
    + "Drake ft. Rick Ross - Money In The Grave (DJ Kuper Edit) V2.mp3\n"
    + "J. Balvin, Willy William & 50 Cent & Tyga & Offset - Gente Candy Taste (Aviel Mymon Mashup).mp3\n"
    + "Jason Derulo Feat. 2 Chainz - Talk Dirty (Buskilaz Remix - Syco Fix).mp3\n"
    + "Jeremih - Down On Me (DALI Edit) .mp3\n"
    + "Kendrik Lamar - Humble (DALI 'migos' Intro).mp3\n"
    + "Lil Pump & Kanye - I love it (Aviel Mymon Prv Edit 2019).mp3\n"
    + "Netta VS Lil Jon - Bassa Mind (Sagi Atia & ShPiz Intro - Aviel Mymon Edit).mp3\n"
    + "Soldi (DALI Private) WOW.mp3\n"
    + "Taiwan MC Ft. Paloma Pradal - Catalina (Gidi Assayag Edit).mp3\n"
    + "Tory Lanez ,Quavo & Tyga - Broke Leg (DJ Kuper Club Edit).mp3\n"
    + "\n"
    + "Reggaeton :\n"
    + "\n"
    + "Anuel AA ft Daddy Yankee, Karol G, J Balvin & Ozuna - China (RooBen Intro).mp3\n"
    + "Anuel AA, Daddy Yankee, Karol G, Ozuna & J. Balvin - China (Dudu A'S Redrum).mp3\n"
    + "Anuel AA, Ozuna - China (Dj Nev Rmx - Itay Ben Senyor Fix).mp3\n"
    + "Daddy Yankee & Snow - Con Calma (Dj Nev Rmx - Itay Ben Senyor Fix).mp3\n"
    + "DJ Snake ft J Balvin & Tyga - Loco Contigo (Aviel Mymon Acapella Edit).mp3\n"
    + "\n"
    + "Remixes :\n"
    + "\n"
    + "Ally Brooke ft A Boogie Wit Da Hoodie - Lips Dont Lie (R3hab Remix).mp3\n"
    + "Billie Eilish - Bad Guy (HUGEL Remix).mp3\n"
    + "Dirty Vegas - Days Go By (CamelPhat Remix).mp3\n"
    + "Ed Sheeran & Justin Bieber - I Don't Care (Jonas Blue Remix).mp3\n"
    + "Eminem  - The Real Slim Shady (DJ Catch Remix).mp3\n"
    + "Ferreck Dawn, Robosonic & Nikki Ambers - In My Arms (Meduza Remix) Clean.mp3\n"
    + "Gwen Stefani - Rich Girl (Jacka Remix).mp3\n"
    + "KVSH, The Otherz, FROEDE - Can't Get Over You (Extended Mix).mp3\n"
    + "Mark Morrison  - Return of the Mack (KAMARENA Remix).mp3\n"
    + "Meduza - Piece Of Your Heart (Dj Dark & MD Dj Remix) [Extended].mp3\n"
    + "Meduza - Piece Of Your Heart (Dj Dark & MD Dj Remix).mp3\n"
    + "Meduza - Piece Of Your Heart (Matthew Hill Remix).mp3\n"
    + "Shawn Mendes, Camila Cabello - Senorita (Dj Dark & MD Dj Remix) [Extended].mp3\n"
    + "Shawn Mendes, Camila Cabello - Senorita (Dj Dark & MD Dj Remix).mp3\n"
    + "Steve Angello & Laidback Luke - Be (D.O.D Remix).mp3\n"
    + "\n"
    + "Singles - סינגלים : \n"
    + "\n"
    + "A$AP Ferg ft MadeinTYO - Wam.mp3\n"
    + "Akon - Wakanda.mp3\n"
    + "Anuel AA ft Daddy Yankee, Karol G, J Balvin & Ozuna - China.mp3\n"
    + "Davido - Fall.mp3\n"
    + "Ed Sheeran & Travis Scott - Antisocial.mp3\n"
    + "Ed Sheeran ft Meek Mill & A Boogie Wit Da Hoodie - 1000 Nights.mp3\n"
    + "Ed Sheeran ft Stormzy - Take Me Back To London.mp3\n"
    + "Iggy Azalea ft Kash Doll - Fuck It Up.mp3\n"
    + "Jhay Cortez - Imaginaste.mp3\n"
    + "Justin Quiles  - Otra Vez.mp3\n"
    + "King Deco ft Mr. Vegas - Castaway (Remix).mp3\n"
    + "Mau & Ricky ft Camilo - La Boca.mp3\n"
    + "YBN Nahmir ft City Girls & Tyga - Fuck It Up.mp3\n"
    + "Yomel El Meloso & Jankobow - Guin Guin.mp3\n"
    + "Yonee ft Jacco Bmbino & Leftside - Get Down.mp3\n"
    + "\n"
    + "Techno - Electo House - Mashup : \n"
    + "\n"
    + "A-Mase & Sharliz - Diamonds (Dudu A'S Edit).mp3\n"
    + "Adam Beyer, Green Velvet, Layton Giordani - Space Date (Pleasurekraft Remix - Syco Fix).mp3\n"
    + "AfterU - Dushanbe (DJ Kuper Edit).mp3\n"
    + "Alesso X Avicii feat Aloe Blacc - SOS Alesso (IdoM Fix).mp3\n"
    + "Amsterdam (Aviel Mymon Fix).mp3\n"
    + "Armin van Buuren & Quintino - This Is What It Feels Like teQno  (Aviel Mymon Mashup).mp3\n"
    + "Armin Van Buuren - Blah Blah Blah (BrainDead Intro - Itay Ben Senyor Fix).mp3\n"
    + "ARTBAT - Element (Aviel Mymon Edit).mp3\n"
    + "Cristian Marchi, Luis Rodriguez - Get Get Down (Doron Shitrit Edit).mp3\n"
    + "Darude - Feel the beat (Aviel Mymon Power Edit) V2.mp3\n"
    + "DJ Antoine X SAMRA - This Time (Ido Keshet Edit).wav\n"
    + "Evanescence & Meduza - Bring Me Body (Braaten & Chrit Leaf Mashup -  IdoM Fix).mp3\n"
    + "Gettoblaster - Future Funk (Aviel Mymon Edit).mp3\n"
    + "Jenia Tarsol - Takadoom (DJ Kuper Blend).mp3\n"
    + "Kevin de Vries - Aratak (Aviel Mymon Fix).mp3\n"
    + "Mahmood - Soldi (Bar Matari & RooBen Remix - Aviel Mymon Intro Edit).mp3\n"
    + "Mahmood - Soldi (Bar Matari & RooBen Remix).mp3\n"
    + "Meduza X Eeemus -  Piece Of Your Heart X Checkmate (Aviel Mymon Mashup).mp3\n"
    + "MOGUA & TouchTalk - Aciiid Laws (Aviel Mymon Mashup).mp3\n"
    + "NWYR - Artificial Intelligence (Itay Ben Senyor Fix).mp3\n"
    + "Oliver Koletzki & Niko Schwind - Subati - Andhim's Electrica Cucar Gidi Assayag Edit.mp3\n"
    + "Rebuke - Along Came Polly (Gidi Assayag Edit).mp3\n"
    + "Samra, Undercover X Samira Said - Biorhythm Mazal (Ido Keshet Edit).mp3\n"
    + "Sllash Doppe - Savanna (IdoM ShortCut).mp3\n"
    + "Space Motion X Meduza - Piece Of Your Epic (Ido Keshet Edit).mp3\n"
    + "Stereo Express - Agatha (Gidi Assayag Edit).mp3\n"
    + "Summer Cem - Tamam Tamam (S?leyman Kaya Remix - IdoM Edit).mp3\n"
    + "Summer Cem - TMM TMM (Ilkay Sencan Remix - RooBen Edit).mp3\n"
    + "Super Flu - Acumulee (Gidi Assayag Edit).mp3\n"
    + "The-Drill Leo Blanco Remix (Itay Ben Senyor Fix).mp3\n"
    + "\n"
    + "ישראלי - מזרחי - דאנס : \n"
    + "\n"
    + "Eden Ben Zaken & Vivo - מאורסת (Aviel Mymon Edit 2019)\n"
    + "Netta - Nana Banana (Liran Hasson Remix - Itay Ben Senyor Fix)\n"
    + "אופק אדנק - טן טן טן (RooBen Redrum)\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - IdoM Edit)\n"
    + "אייל גולן - ג'ונגל (Yonatan Harlev 2019 Remix - Aviel Mymon Edit)\n"
    + "אייל גולן - ג'ונגל (Yonatan Harlev 2019 Remix - Itay Ben Senyor Fix)\n"
    + "אייל גולן ובניה ברבי - ממה את מפחדת (Shon Hen Remix - Itay Ben Senyor Fix)\n"
    + "איתי לוי - טכנו (Alon Mix & Yaki-E. - A'S Edit)\n"
    + "איתי לוי - טכנו (Alon mix Remix - Itay Ben Senyor Fix)\n"
    + "איתי מולו & שאנטי וטזרה - קודם כל (RooBen Redrum)\n"
    + "אליעד - מסע (Sharon Yosefov Remix - Aviel Mymon Fix)\n"
    + "מושיקו מור - הניחי לי (RooBen - Itay Ben Senyor Fix)\n"
    + "מושיקו מור - הניחי לי (RooBen Intro - Itay Ben Senyor Fix)\n"
    + "סטפן לגר-כפרה (Doron Shitrit Remix - Itay Ben Senyor Fix)\n"
    + "סטפן לגר-כפרה (Doron Shitrit Remix) V2\n"
    + "עדן בן זקן & עדן חסון - שונה מהנוף (Yosefov Remix - Itay Ben Senyor Fix)\n"
    + "עדן בן זקן - תרימו (Jetfire Wedding Edit - Itay Ben Senyor Fix)\n"
    + "עדן בן זקן ועדן חסון - שונה מהנוף (Roi Harush - Dudu A'S Edit)\n"
    + "עדן חסון - איך את אוהבת (Doron Shitrit Remix) V3\n"
    + "עומר אדם - טמפרטורה (Doron Shitrit Remix) V2\n"
    + "עומר אדם - טמפרטורה (Doron Shitrit Remix) V5\n"
    + "עומר אדם - טמפרטורה X מקרנה (Doron Shitrit Remix) Fixed\n"
    + "עומר אדם - יעשו לנו כבוד (Loren Benisty Remix - Gidi Assayag Edit)\n"
    + "עומר אדם - יעשו לנו כבוד (M!rel & Lubinski Remix - Aviel Mymon Edit)\n"
    + "עומר אדם - יעשו לנו כבוד - Loren Benisty Remix (Gidi Assayag Darbuka) Intro\n"
    + "עומר אדם - רק תגידו לה ( DEAN BARAK INTRO REMIX - Itay Ben Senyor Fix)\n"
    + "עומר אדם - שני משוגעים (Gidi Assayag Darbuka Remix) V2\n"
    + "רועי סנדלר - הכל בסדר (Eden Shalev Remix - Aviel Mymon Edit)\n";


  private itemsPlaylist: { [key: string]: string } = {
    "teamixVol19": this.teamixVol19, "teamixVol18": this.teamixVol18, "teamixVol17": this.teamixVol17, "teamixVol16": this.teamixVol16,
    "teamixVol15": this.teamixVol15, "teamixVol14": this.teamixVol14, "teamixVol13": this.teamixVol13, "teamixVol12": this.teamixVol12,
    "teamixVol11": this.teamixVol11, "teamixVol10": this.teamixVol10, "teamixVol9": this.teamixVol9, "teamixVol8": this.teamixVol8,
    "teamixVol7": this.teamixVol7, "teamixVol6": this.teamixVol6, "teamixVol5": this.teamixVol5, "teamixVol4": this.teamixVol4,
    "teamixVol3": this.teamixVol3, "teamixVol2": this.teamixVol2, "teamixVol1": this.teamixVol1
  };


  public getItemsPlaylist(): { [key: string]: string } {
    return this.itemsPlaylist;
  }


}
