import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ItemsPlaylistService {

  constructor() { }

  private teamixVol1 = "";
  private teamixVol2 = "";
  private teamixVol3 = "";
  private teamixVol4 = "";
  private teamixVol5 = "";
  private teamixVol6 = "";
  private teamixVol7 = "";
  private teamixVol8 = "";
  private teamixVol9 = "";
  private teamixVol10 = "";
  private teamixVol11 = "";
  private teamixVol12 = "";
  private teamixVol13 = "";
  private teamixVol14 = "";

  private teamixVol15 =
    "Armin van Buuren - Turn It Up (Aviel Mymon Fix)\n"
    + "ARTBAT - Upperground (Aviel Mymon Fix)\n"
    + "Agnez Mo ft. Chris Brown & Juicy J - Overdose (TSD Remix - DJ Kuper Edit)\n"
    + "Ardian Bujupi Ft. Farruko y Xhensila - Cika Cika (RooBen Intro)\n"
    + "Ariana Grande - 7 Rings (Robert Cristian Remix - Dudu A'S Edit)\n"
    + "ATB X Roei Malka - 9PM (RooBen Mashup)\n"
    + "Bolier, Trobi - In The Water (Sagiv Alfasi Edit)\n"
    + "Camila Cabello - Havana (Sagi Kariv Remix - Dudu A'S Edit)\n"
    + "Carlos Vives Ft. Wisin - Si Me Das Tu Amor (RooBen Intro) Hook 1st\n"
    + "Carlos Vives Ft. Wisin - Si Me Das Tu Amor (RooBen Intro)\n"
    + "Clean Bandit feat. Ellie Goulding - Mama (Syco Edit) V1\n"
    + "Clean Bandit feat. Ellie Goulding - Mama (Syco Edit) V2\n"
    + "Confieso - F4ST (Sagiv Alfasi Edit)\n"
    + "Diplo - Oh Maria (Syco Intro)\n"
    + "Drake - One Dance (Moshe Buskila - Dudu A'S Intro)\n"
    + "Eleni Foureira - Fuego (DJ Kuper Edit)\n"
    + "German Avny & Mike Tsoff - Believe (Extended Mix)\n"
    + "German Avny & Mike Tsoff - Believe (Radio Mix)\n"
    + "Hellm8 vs. SMVGGLERS - Freedom (Sagiv Alfasi Short Edit)\n"
    + "?Insideeus - Bubble On Me (RooBen Intro)\n"
    + "J Balvin - Ay Vamos (RooBen Redrum)\n"
    + "Jenia & Jinga & Sagi Kariv - TakaDoom (RooBen Mashup)\n"
    + "Krept & Konan ft Jeremih - Freak Of The Week (DJ Kuper Intro)\n"
    + "Lady Gaga Ft. Bradley Cooper - Shallow (Nesco Remix - A'S Edit)\n"
    + "Maluma - HP (RooBen Intro)\n"
    + "Marwa Loud - Bad Boy (DJ Kuper Edit)\n"
    + "Migos ft. Lil Uzi Vert - Bad And Boujee (DJ Kuper Transition) 80-63\n"
    + "Nacho - Nadie Sabe (RooBen Intro)\n"
    + "Nicky Jam Ft. Ozuna - Te Robare (RooBen Redrum)\n"
    + "Offer Nissim - Esther (Dudu A'S Edit)\n"
    + "Ozuna Feat. Akon - Coméntale (Aviel Mymon Intro)\n"
    + "Rauf & Faik - Детство (Rakurs & Eddie G Remix - Syco Fix)\n"
    + "Shakedown - At Night (Purple Disco Machine Extended Remix - IdoM Edit)\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V1\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V2\n"
    + "Shasha - Shasha Sar Lah (Buskilaz Remix - Syco Fix) V3\n"
    + "Sllash & Doppe - Aguella (Aviel Mymon Fix)\n"
    + "Technotronic - Pump Up The Jam 19 (Sergey Kutsuev Remix - Dudu A'S Edit) 125 BPM\n"
    + "The Weeknd - I Cant Feel My Face (DJ Kuper Transition) 125-108\n"
    + "Tropkillaz Ft. J Balvin, Anitta y MC Zaac - Bola Rebola (RooBen Intro)\n"
    + "The Prince Karma - Later Bitches (Aviel Mymon Intro)\n"
    + "Tyga - Rack City (DJ Kuper Edit)\n"
    + "Wyclef Jean & Missy Elliott - Party To Damascus (DJ Kuper Intro)\n"
    + "אייל גולן - הפוך מהיקום (Dudu A'S Redrum)\n"
    + "אייל גולן ועופר ניסים - לא מבינה עברית (Guy Raz Remix - Dudu A'S Edit)\n"
    + "אניה בוקשטיין ועופר ניסים - רוקדת (RooBen Fix)\n"
    + "דודו אהרון - הלב שלי על מאתיים (RooBen Mashup) V2\n"
    + "דודו אהרון - הלב שלי על מאתיים (RooBen Mashup) V3\n"
    + "עדן בן זקן - תגיד לי (RooBen Mashup)\n"
    + "עומר אדם - תגידי לי שטוב לך (BlazE & Matan Amar Remix - RooBen Short Edit)\n"
    + "עדן חסון - שיכורים (Mor David X Yonatan Harlev - Aviel Mymon Fix)\n";

  private teamixVol16 =
    "4 Strings vs. Sick Inviduals & Holl & Rush - Take Me Away (German Avny Mashup)\n"
    + "Age Of Love - The Age Of Love (Solomun Renaissance - Gidi Assayag Edit)\n"
    + "Age Of Wena Paradise (Gavri Blend X Or Pilo - Aviel Mymon Intro Edit)\n"
    + "Alan Walker, Sabrina Carpenter & Farruko - On My Way (Mike Tsoff & German Avny Remix)\n"
    + "Arm In Arm - Hunger For Your Vibe (Moonwalk Remix - Gidi Assayag Edit)\n"
    + "ARTBAT - Upperground (Gidi Assayag Edit)\n"
    + "Avicii ft Aloe Blacc - SOS (RooBen Intro)\n"
    + "Chris Brown ft. Nicki Minaj & G-Eazy - Wobble Up (DJ Kuper Intro)\n"
    + "City Girls - Act Up (RooBen Intro)\n"
    + "Cola X Trance 7 (Aviel Mymon Power Edit)\n"
    + "Dennis Lloyd - Never Go Back (RooBen Private Redrum)\n"
    + "Duke Dumont - Red Light Green Light (IdoM Edit)\n"
    + "Eleni Foureira - Fuego (DJ Kuper Edit)\n"
    + "Infected Mushroom, WARRIORS vs. Rozalla - Becoming Insane (German Avny Mashup)\n"
    + "Jayh - Fluister (RooBen Edit)\n"
    + "Loni - Loneliness (Gidi Assayag Edit)\n"
    + "Madonna Ft. Maluma - Medellín (RooBen Redrum)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (DJ Kuper Intro)\n"
    + "Natti Natasha Y Anitta - Te Lo Dije (RooBen Intro)\n"
    + "Niels Van Gogh - Pulverturm (Tiesto Remix - Gidi Assayag Edit)\n"
    + "Offer Nissim - Alone (German Avny Mashup)\n"
    + "Post Malone & Swae Lee - Sunflower (Panic City Remix - DJ Kuper Fix)\n"
    + "Rej3ctz - Baby Shark (Twerk Remix - Tommy K. & DJ Kuper Edit)\n"
    + "Sagiv Alfasi - Independence Day (Israel VS Dana)\n"
    + "Saturator X עומר אדם -יעשו לנו כבוד (Sagiv Alfasi Mashup)\n"
    + "Space Motion - Epic (Gidi Assayag Edit)\n"
    + "ToMix & Genish - Lam Gana Poo (RooBen Fix)\n"
    + "Tyga - Goddamn (RooBen Intro)\n"
    + "Warp brothers and Aquagen vs. Alexx Slam - Blade (German Avny Mashup)\n"
    + "Zivert - Life (German Avny & Mike Tsoff Remix)\n"
    + "אייל גולן - לרקוד כמו משוגע (Daniel Remix - Dudu A'S Edit)\n"
    + "אייל גולן - שיכור בלילות (Dudu A'S Darbuka Remix)\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - RooBen Fix)\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - Syco Edit) V2\n"
    + "אייל גולן & בניה ברבי - ממה את מפחדת (Raz Moyal Remix - Syco Edit)\n"
    + "אייל גולן X Vivo - לרקוד כמו משוגע (Daniel Remix - Aviel Mymon Fix)\n"
    + "איתי לוי - קעקוע על הלב (Daniel Remix - Aviel Mymon Fix)\n"
    + "יעל מאס מארחת את צגאי בוי - גודטיים (RooBen Intro)\n"
    + "מושיקו מור - תסביכים (Kobi Shaltiel Remix - Syco Fix) V1\n"
    + "מושיקו מור - תסביכים (Kobi Shaltiel Remix - Syco Fix) V2\n"
    + "מירי מסיקה - מפחד עלייך (DANIELRemix - RooBen Fix)\n"
    + "משה פרץ - מתי (Dudu A'S Redrum)\n"
    + "נוי פדלון - מפחיד (IdoM & Roby Fayer Intro)\n"
    + "נוי פדלון - מפחיד (RooBen Intro) Hook 1st\n"
    + "נתן גושן - מתגעגעת (Dudu A'S Redrum)\n"
    + "סטפן לגר ואופק המלאך - יום הולדת (RooBen Intro)\n"
    + "עומר אדם - יעשו לנו כבוד (Gidi Assayag Remix)\n"
    + "עומר אדם - יעשו לנו כבוד (Mor David Remix - Syco Fix)\n"
    + "צפריר יפרח וסמואל שובל - דרבוקה (Dudu A'S Long Edit)\n"
    + "צפריר יפרח וסמואל שובל - דרבוקה (Dudu A'S Short Edit)\n"
    + "שרית חדד ועופר ניסים - SHUFUNI (Aviel Mymon Intro)\n";

  private teamixVol17 =
    "Alan Walker, Sabrina Carpenter & Farruko - On My Way (RooBen Redrum) 97\n"
    + "Alex Guesta - Akachi (Sagiv Alfasi Edit )\n"
    + "Ava Max - Sweet But Psycho (Dark & Adrian - Dudu A'S Edit)\n"
    + "Backstreet Boys X Krajno - I Want It In Anatolia Way (Skeletron - IdoM Edit)\n"
    + "Blastoyz, Reality Test - Kabalah (Sagiv Alfasi Edit)\n"
    + "Corinda, AfroTura - Aso (RooBen Fix)\n"
    + "Daddy Yankee x Balkan Beat Box - Shaky Shaky (IdoM Edit)\n"
    + "Daniel Portman - Casa Rumba (Sagiv Alfasi Edit)\n"
    + "Dimitri Vegas, Like Mike, Liquid Soul, Vini Vici - Untz Untz (Sagiv Alfasi Edit)\n"
    + "DJ Snake Ft. Selena , Cardi B & Ozuna - Taki Taki (Sharon Yosefov - A'S Intro)\n"
    + "DJ Snake x Ozuna x Cardi B x Lowderz & Zuffo - Taki Taki Blend (IdoM EDIT) 125-100\n"
    + "Dor Mor - Clock (Gidi Assayag Edit)\n"
    + "Dua Lipa X Thomas Gold - One Kiss Orinoco (Aviel Mymon Mashup)\n"
    + "Ed Sheeran & Justin Bieber - I Don't Care (RooBen Redrum)\n"
    + "French Montana ft. Blueface & Lil Tjay - Slide (DJ Kuper Intro)\n"
    + "Gigi D'Agostino - In My Mind (German Avny & Mike Tsoff - Gidi Assayag Edit)\n"
    + "Hechizeros Band vs DJ Willie - El Sonidito (Make Some Noise Bootleg - Gidi Assayag Edit)\n"
    + "Kanye West & Lil Pump Vs. The Kemist & Braindead Ft. Nyanda - I Love It (Dudu A'S Fix)\n"
    + "KAZKA - Cry (R3HAB Remix - RooBen Power Edit)\n"
    + "Loni - Loneliness (Sagiv Alfasi Edit )\n"
    + "Losless - Synecku - (Gidi Assayag Long Edit)\n"
    + "Losless - Synecku - (Gidi Assayag Short Edit)\n"
    + "Luca Hanni - She Got Me (RooBen Redrum) Eurovision 2019\n"
    + "Lunay Ft Daddy Yankee & Bad Bunny - Soltera (RooBen Intro)\n"
    + "Mahmood - Soldi (Denis First - Dudu A'S Edit)\n"
    + "Mahmood - Soldi (Denis First Remix - Gidi Assayag Edit)\n"
    + "Mahmood - Soldi (Syco Intro)\n"
    + "Maitre Gims ft. Maluma - Hola Senorita (RooBen Redrum\n"
    + "Mann ft. 50 Cent - Buzzin (Remix) (DJ Kuper Edit)\n"
    + "Marshmello, Chris Brown, Tyga - Light It Up (DALI Intro)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (DJ Kuper Intro)\n"
    + "Marshmello, Tyga & Chris Brown - Light It Up (Gidi Assayag Acapella Out Edit)\n"
    + "Meek Mill ft. Ella Mai - 24_7 (DJ Kuper Intro)\n"
    + "Monolink - Return to Oz (Artbat Remix - Gidi Assayag Long Edit)\n"
    + "Monolink - Return to Oz (Artbat Remix - Gidi Assayag Short Edit)\n"
    + "Moonwalk - Galactic (Stil Vor Talent Remix - Aviel Mymon Edit)\n"
    + "Netta VS Lil Jon - Bassa Mind (Sagi Atia & ShPiz Intro - Aviel Mymon Edit)\n"
    + "Olivier Giacomotto - Bipolar Star (Victor Ruiz Remix - Aviel Mymon Fix)\n"
    + "OT Genasis - Bae (DJ Kuper Transition) 80-101\n"
    + "Panic! At The Disco - High Hopes (RooBen Private Mashup)\n"
    + "Tokyo Drift X Tempera (Aviel Mymon Edit)\n"
    + "Trance Wax & Omer Adam - Trance 7 (DJ Kuper 'Tagidi Li She Tov' Edit)\n"
    + "Tyga - Goddamn (DALI Intro) V1\n"
    + "Tyga - Goddamn (DALI Intro) V2\n"
    + "WW x Vini Vici - SHAMELESS Chakra (MANI - IdoM Edit)\n"
    + "Zedd, Katy Perry - 365 (German Avny & Mike Tsoff Remix)\n"
    + "ZENA - Like It (RooBen Redrum) Eurovision 2019\n"
    + "מושיקו מור - הניחי לי (RooBen Intro Redrum)\n"
    + "מושיקו מור - הניחי לי (RooBen Redrum)\n"
    + "עדן חסון - כפיות (Mor David Remix - IdoM Edit)\n"
    + "עומר אדם - יעשו לנו כבוד (Shon Hen Remix - Aviel Mymon Edit)\n"
    + "פאר טסי - מי אני (Dudu A'S Redrum)\n";

  private teamixVol18 =
    "Exclusive :\n"
    + "\n"
    + "Chen Leiba - Leibailar (Shon Hen Official Remix).wav\n"
    + "Chen Leiba - Leibailar (Shon Hen Remix - RooBen Fix).mp3\n"
    + "Chen Leiba Ft.Tomer Aaron - Mabruk Alekha (Original Mix).mp3\n"
    + "Chen Leiba, Chen Mantsoor, Sivan - Electrafied (Extended).mp3\n"
    + "Eli Arbiv, Chen Leiba - Nothing's Stopping Me (Extended).mp3\n"
    + "German Avny - Gaya (Extended Mix).mp3\n"
    + "German Avny - Gaya (Original Mix).mp3\n"
    + "\n"
    + "Hip Hop - Dancehall - Pop :\n"
    + "\n"
    + "Charly Black X Nicky Jam & J Balvin X RooBen - Party X (Aviel Mymon Edit).mp3\n"
    + "Kamaiyah ft. Tyga & Quavo - Windows (DJ Kuper Transition) (Tyga First) 80-100.mp3\n"
    + "Kanye West Lil Pump X Usher - I Love it Yeah (Sagiv Alfasi Break Mash-up).mp3\n"
    + "King Deco X Sean Paul - Castaway (Don't Leave Me) (RooBen Edit).mp3\n"
    + "Lil Nas X - Old Town Road (DJ Kuper Aca In).mp3\n"
    + "Lil Nas X - Old Town Road (RooBen Redrum) Acapella In.mp3\n"
    + "Meek Mill ft. Ella Mai - 24_7 (DJ Kuper Intro).mp3\n"
    + "Nicki Minaj X Mr Vegas - Megatron (RooBen Edit).mp3\n"
    + "OT Genasis - Bae (DJ Kuper Transition) 80-101.mp3\n"
    + "Starboy - Soco (DJ Kuper Aca In).mp3\n"
    + "Tyga ft. J Balvin & Chris Brown - Haute (DJ Kuper Intro).mp3\n"
    + "Young Thug ft. J. Cole & Travis Scott - The London (DJ Kuper Transition) 75-98.mp3\n"
    + "\n"
    + "Reggaeton :\n"
    + "\n"
    + "Borja Rubio Y Juan Magan - Y Si Te Beso, Que (RooBen Intro) Hook 1st.mp3\n"
    + "Borja Rubio Y Juan Magan - Y Si Te Beso, Que (RooBen Intro).mp3\n"
    + "Jhay Cortez, J Balvin Y Bad Bunny - No Me Conoce (RooBen Intro) Hook 1st.mp3\n"
    + "Maluma - HP (Mor David Remix - Itay Ben Senyor Fix).mp3\n"
    + "Taki Taki X הניחי לי (Or Pilo Mashup - Itay Ben Senyor Fix).mp3\n"
    + "\n"
    + "Techno - Electo House - Mashup :\n"
    + "\n"
    + "Age Of Love - The Age Of Love (Solomun Renaissance - Gidi Assayag Edit).mp3\n"
    + "Alex Guesta, Benzly Hype, Raphael - Dance 4 Me (Paul Jockey Remix - Sagiv Alfasi Edit).mp3\n"
    + "Bipolar Star (Victor Ruiz Remix - Itay Ben Senyor Fix).mp3\n"
    + "El Mundo Zazou - Can You See What I See Elfenberg Remix (Sagiv Alfasi Edit).mp3\n"
    + "Evokings - On The Floor (Aviel Mymon Fix).wav\n"
    + "Extinct X Jax Jones - Lose Yourself (Jonni M Mashup - Aviel Mymon ReWork Edit).mp3\n"
    + "Gettoblaster - Future Funk (Itay Ben Senyor Fix).mp3\n"
    + "Hardwell & Franky Rizardo - Asteroid (Aviel Mymon Edit).mp3\n"
    + "Jako Vs Work (Ofek Yom Tov & Roie Malka Mash - Itay Ben Senyor Fix).mp3\n"
    + "Jenia & Jinga - Takadoom (Lidor Zirk Remix - Itay Ben Senyor Edit).mp3\n"
    + "Komodo - (I Just) Died In Your Arms (German Avny & Mike Tsoff Remix).mp3\n"
    + "K£ra - Gogo (Nathan Thomson Remix - Itay Ben Senyor Fix).mp3\n"
    + "Layton Giordani - Drumcode (Itay Ben Senyor Fix).mp3\n"
    + "Meduza ft. Goodboys - Piece Of Your Heart (Syco Edit).mp3\n"
    + "Sunnery James Ryan Marciano - Yeke Yeke (Sagiv Alfasi Avira Edit).mp3\n"
    + "Timmy Trumpet x Cardi B - I Like Al Pacino (Aviel Mymon Mashup).mp3\n"
    + "Zafrir Ifrach - Mama Daili ft. Naj (Syco Extended).mp3\n"
    + "\n"
    + "ישראלי - מזרחי - דאנס :\n"
    + "\n"
    + "Ido Shoam & Hovevi Tzion - Rotze Banot (Syco Edit).mp3\n"
    + "Mor Avrahami ft Izhar Cohen - Abanibi (Sagiv Alfasi Edit).mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V1.mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V2.mp3\n"
    + "Netta - Nana Banana (MASH Remix - Syco Fix) V3.mp3\n"
    + "Stephane Legar - Kapara (Rotem Baum Rmx - Syco Edit) V1.mp3\n"
    + "Stephane Legar - Kapara (Rotem Baum Rmx - Syco Edit) V2.mp3\n"
    + "אגם בוחבוט - בננות (RooBen Redrum)\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro) Acapella In\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro) Hook 1st\n"
    + "אדיר גץ וקריזמו - אובססיון (RooBen Intro)\n"
    + "אייל גולן - אוסף עוד געגוע (Dudu A'S Redrum)\n"
    + "אייל גולן ובניה ברבי - ממה את מפחדת (Eli Arbiv Intro Remix - Itay Ben Senyor Fix)\n"
    + "אייל גולן ובניה ברבי - ממה את מפחדת (Eli Arbiv Remix - Itay Ben Senyor Fix)\n"
    + "איתי לוי - קעקוע על הלב (DANIEL Remix - Itay Ben Senyor Fix)\n"
    + "אליעד - מסע (Dudu A'S Redrum)\n"
    + "אליעד - מסע (Sharon Yosefov - Dudu A'S No Drop Edit)\n"
    + "אליעד - מסע (Yosefov Remix - Itay Ben Senyor Fix) V2\n"
    + "אליעד - מסע (Yosefov Remix - Itay Ben Senyor Fix)\n"
    + "גל מלכה & אקסום & אבי היילו - לה לה (RooBen Private Edit)\n"
    + "דודו אהרון ואיתי לוי - השמחה שלנו (Sharon Yosefov Remix - Itay Ben Senyor Fix)\n"
    + "נועה קירל - חצוף (RooBen Edit)\n"
    + "סטטיק ובן אל תבורי - בננות (Dudu A'S Redrum)\n"
    + "עדן בן זקן - תגיד לי (Yohan Cohen Remix - Itay Ben Senyor Fix)\n"
    + "עדן בן זקן & עדן חסון - שונה מהנוף (Dudu A'S Redrum)\n"
    + "עדן בן זקן & עדן חסון - שונה מהנוף (RooBen Redrum)\n"
    + "עדן חסון - איך את אוהבת (Mor David Remix - Itay Ben Senyor Fix)\n"
    + "עדן חסון - אין יותר מועדונים (Alon Mix & Yaki - E Remix - Itay Ben Senyor Fix)\n"
    + "עומר אדם - טמפרטורה (Dudu A'S Redrum)\n"
    + "עומר אדם - יעשו לנו כבוד (RooBen Private Mashup)\n"
    + "עומר אדם - תתן לה פרחים (Dudu A'S Redrum)\n"
    + "עומר-אדם - לרקוד ולזוז (Sharon Yosefov Remix - Sagiv Alfasi Edit) 105-128\n";

  private teamixVol19 = "";
  private teamixVol20 = "";
  private teamixVol21 = "";
  private teamixVol22 = "";


  private itemsPlaylist: { [key: string]: string } = { "teamixVol15": this.teamixVol15, "teamixVol16": this.teamixVol16, "teamixVol17": this.teamixVol17, "teamixVol18": this.teamixVol18 };


  public getItemsPlaylist(): { [key: string]: string } {
    return this.itemsPlaylist;
  }


}
